import { Injectable, signal } from '@angular/core';
import { Internship, Certification, Education, SkillCategory, Project, ContactInfo } from '../../models/portfolio.model';

@Injectable({
  providedIn: 'root',
})
export class PortfolioService {
  readonly profile = signal({
    name: 'Namala Harshitha',
    initials: 'NH',
    role: 'Full Stack Developer',
    headlineSubtext: 'Architecting scalable web applications, robust microservices, and reactive high-performance user experiences.',
    shortBio: `I am an enthusiastic Full Stack Developer with deep expertise in Angular, TypeScript, Node.js, and modern cloud ecosystems. Passionate about clean code architecture, reactive state management with Angular Signals, and building resilient distributed systems that deliver exceptional speed and delightful UX.`,
    location: 'Bengaluru, India / Remote Worldwide',
    email: 'harshithanamala04@gmail.com',
    phone: '+91 9441283233',
    github: 'https://github.com/harshithanamala04',
    linkedin: 'https://www.linkedin.com/in/harshitha-namala-a0a482318',
    stats: [
      { label: 'Years Experience', value: '3+' },
      { label: 'Completed Projects', value: '25+' },
      { label: 'Code Commits', value: '1.2k+' },
      { label: 'Uptime Reliability', value: '99.9%' },
    ],
  });

  readonly internships = signal<Internship[]>([
    {
      id: 'infosys-virtual',
      company: 'Infosys Springboard',
      role: 'Python Full Stack Intern',
      period: 'Currently Ongoing',
      location: 'Virtual / Remote',
      type: 'Internship',
      status: 'Currently Ongoing',
      summary: 'Building a Patient Management System with Django and Django REST Framework, integrating Firebase for secure authentication and real-time backend data storage.',
      featured: true,
      logoUrl: '/logos/infosys_logo.png',
    },
    {
      id: 'techwing',
      company: 'Techwing',
      role: 'Frontend / Full Stack Intern',
      period: 'May 2026 - Aug 2026',
      location: 'Rajahmundry, India',
      type: 'Internship',
      status: 'Completed',
      summary: 'Engineered modular and responsive client-side interfaces using Angular and TypeScript, implementing clean custom styling and consuming backend RESTful services.',
      featured: true,
      logoUrl: '/logos/techwing_logo.png',
      certificateUrl: '/certificates/techwing_internship.png',
      certificatePdf: '/certificates/techwing_internship.pdf',
      certificateTitle: 'Certificate of Internship: AWS + JFS',
    },
    {
      id: 'apssdc',
      company: 'APSSDC',
      role: 'Data Analysis Intern',
      period: 'Apr 2025 - Jun 2025',
      location: 'Andhra Pradesh, India',
      type: 'Internship',
      status: 'Completed',
      summary: 'Analyzed and visualized Electric Vehicle (EV) charging patterns using Python libraries, generating clear behavioral insights through exploratory data analysis.',
      featured: true,
      logoUrl: '/logos/apssdc_logo.png',
      certificateUrl: '/certificates/apssdc_internship.png',
      certificatePdf: '/certificates/apssdc_internship.pdf',
      certificateTitle: 'Data Analysis Using Python',
    },
  ]);

  readonly certifications = signal<Certification[]>([
    {
      id: 'infosys-pragati-cohort',
      title: 'Pragati: Path to Future - Cohort 8',
      issuer: 'Infosys Springboard',
      issueDate: '2026',
      previewUrl: '/certificates/infosys_pragati_internship.png',
      description: 'Completed Infosys Springboard Pragati Cohort 8, gaining in-depth knowledge in Python programming, AIML, Data Science foundations, and professional communication skills.',
    },
    {
      id: 'infosys-python-basics',
      title: 'Basics of Python',
      issuer: 'Infosys Springboard',
      issueDate: 'May 2, 2026',
      previewUrl: '/certificates/infosys_python_basics.png',
      description: 'Course completion certification in Python programming fundamentals, algorithmic control structures, functions, and standard libraries.',
    },
    {
      id: 'infosys-python-oop',
      title: 'Object Oriented Programming using Python',
      issuer: 'Infosys Springboard',
      issueDate: 'May 3, 2026',
      previewUrl: '/certificates/infosys_python_oop.png',
      description: 'Course completion credential in object-oriented architecture in Python: encapsulation, classes, inheritance, polymorphism, and modular design.',
    },
  ]);

  readonly skillCategories = signal<SkillCategory[]>([
    {
      title: 'Frontend',
      skills: ['Angular', 'TypeScript', 'HTML', 'CSS', 'SCSS'],
    },
    {
      title: 'Backend & Security',
      skills: ['Python', 'Django', 'Django REST API', 'JWT & OAuth2 Security'],
    },
    {
      title: 'Databases & Cloud',
      skills: ['MySQL', 'SQL', 'DBMS', 'Supabase', 'Firebase'],
    },
    {
      title: 'Tools & Version Control',
      skills: ['Git', 'GitHub', 'VS Code'],
    },
  ]);

  readonly education = signal<Education[]>([
    {
      id: 'btech',
      degree: 'B.Tech in Data Science',
      institution: 'Godavari Institute of Engineering and Technology (GIET)',
      status: 'Final Year Student',
      period: '2023 – 2027',
      score: '9.5 / 10',
      scoreLabel: 'CGPA',
      description: 'Final year student specializing in Data Science with a core focus on end-to-end software engineering.',
    },
    {
      id: 'inter',
      degree: 'Intermediate (12th Grade)',
      institution: 'Sri Chaitanya College',
      status: 'Completed',
      period: '2021 – 2023',
      score: '95.6%',
      scoreLabel: 'Percentage',
      description: 'Completed Intermediate education with distinction, securing 95.6% out of 100.',
    },
    {
      id: 'tenth',
      degree: 'Secondary School (10th Grade)',
      institution: 'Dr. KKR Gowtham Concept School',
      status: 'Completed',
      period: '2021',
      score: '99%',
      scoreLabel: 'Percentage',
      description: 'Completed secondary schooling at Dr. KKR Gowtham Concept School, achieving an outstanding 99%.',
    },
  ]);

  readonly projects = signal<Project[]>([
    {
      id: 'healio-mgmt',
      title: 'Healio – Patient Management System',
      category: 'Full Stack',
      tagline: 'Healthcare records & appointment management portal',
      description: 'Healthcare portal for booking appointments and managing electronic medical records.',
      highlights: [
        'Built with responsive frontend architecture and real-time appointment scheduling.',
        'Integrated patient health tracking, prescription logs, and vital status telemetry.',
      ],
      techStack: ['Angular', 'Django REST', 'Firebase'],
      liveUrl: 'http://healio-app-black.vercel.app',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/healio_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-emerald-600 via-teal-600 to-cyan-700',
      accentColor: '#059669',
    },
    {
      id: 'ai-resume-analyzer',
      title: 'AI Resume Analyzer',
      category: 'Full Stack',
      tagline: 'Smart ATS scoring, resume analysis & skill insights',
      description: 'AI-powered resume analyzer evaluating ATS compatibility, skill matching, and tailored optimization recommendations.',
      highlights: [
        'Automated resume parsing with instant ATS score benchmarking and keyword matching.',
        'Actionable AI feedback on skill gaps, formatting improvements, and job alignment.',
      ],
      techStack: ['Python', 'Streamlit', 'NLP', 'AI / LLM'],
      liveUrl: 'https://ai-resume-analyzer-hmcdxvthfzk2etdeakksgr.streamlit.app/',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/ai_resume_analyzer_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-violet-600 via-purple-600 to-indigo-700',
      accentColor: '#7c3aed',
    },
    {
      id: 'freshcart',
      title: 'FreshCart – Fresh Fruits and Veggies',
      category: 'Frontend',
      tagline: 'Farm-fresh 100% organic produce delivery store',
      description: 'Interactive grocery storefront featuring live cart management and category filters.',
      highlights: [
        'Interactive product catalog with category filtering and instant price updates.',
        'Dynamic cart state management supporting quantity adjustments and instant totals.',
      ],
      techStack: ['Angular', 'TypeScript', 'Firebase'],
      liveUrl: 'https://freshcart-3b848.web.app',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/freshcart_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-green-600 via-emerald-600 to-teal-700',
      accentColor: '#10b981',
    },
    {
      id: 'sri-rudra-store',
      title: 'Sri Rudra Online Store',
      category: 'Full Stack',
      tagline: 'Authentic groceries & general store application',
      description: 'E-commerce platform for browsing authentic products and seamless checkout.',
      highlights: [
        'Multi-category catalog featuring authentic groceries, grains, spices, and daily essentials.',
        'Smooth cart management, search filtering, and user-friendly checkout flows.',
      ],
      techStack: ['Angular', 'Tailwind CSS', 'Vercel'],
      liveUrl: 'https://sri-rudra-online-store.vercel.app/',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/sri_rudra_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-amber-600 via-orange-600 to-rose-700',
      accentColor: '#d97706',
    },
    {
      id: 'pricewise-ai',
      title: 'PriceWise AI – Price Comparison',
      category: 'Full Stack',
      tagline: 'AI-powered product price comparison platform',
      description: 'AI-powered product price comparison platform across online marketplaces to find top deals.',
      highlights: [
        'Aggregates real-time product prices across major e-commerce platforms.',
        'Intelligent deal discovery and price-drop tracking alerts.',
      ],
      techStack: ['AI Search', 'Price Tracker', 'Web App'],
      liveUrl: 'https://pricewise-ai-be26e.web.app/',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/pricewise_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-blue-600 via-indigo-600 to-cyan-600',
      accentColor: '#2563eb',
    },
    {
      id: 'hercycle-tracker',
      title: 'HerCycle – Menstrual & Wellness Tracker',
      category: 'Frontend',
      tagline: 'Menstrual cycle and wellness tracking application',
      description: "Menstrual cycle and women's wellness tracking application for cycles, symptoms, and health insights.",
      highlights: [
        'Interactive cycle calendar with predictive ovulation and symptom logging.',
        'Personalized wellness insights and mood monitoring telemetry.',
      ],
      techStack: ['Next.js', 'Health Tech', 'Analytics'],
      liveUrl: 'https://hercycle-tracker.vercel.app?utm_source=chatgpt.com',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/hercycle_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-pink-500 via-rose-500 to-purple-600',
      accentColor: '#db2777',
    },
    {
      id: 'text-to-sql-translator',
      title: 'Text to SQL Generator',
      category: 'Full Stack',
      tagline: 'Type what you want in plain English, and get the exact SQL query instantly',
      description: 'Free AI-powered Text-to-SQL generator that translates plain English questions into executable SQL queries with instant query explanations.',
      highlights: [
        'Translates natural language questions into accurate SQL queries instantly with zero API key required.',
        'Features query logic breakdowns, Gemini AI integration, and multi-table SQL generation.',
      ],
      techStack: ['Python', 'Streamlit', 'Gemini AI', 'SQL'],
      liveUrl: 'https://text-to-sql-translator-b392abrajd5xc3j2hdfg3k.streamlit.app/',
      githubUrl: 'https://github.com/harshithanamala04',
      featured: true,
      imageUrl: '/projects/text_to_sql_preview.jpg',
      metrics: { label: 'Status', value: 'Live' },
      gradient: 'from-sky-500 via-blue-600 to-indigo-600',
      accentColor: '#0284c7',
    },
  ]);

  readonly contactDetails = signal<ContactInfo[]>([
    {
      type: 'email',
      label: 'Email',
      value: 'harshithanamala04@gmail.com',
      link: 'mailto:harshithanamala04@gmail.com',
      icon: 'mail',
    },
    {
      type: 'phone',
      label: 'Contact Number',
      value: '+91 9441283233',
      link: 'tel:+919441283233',
      icon: 'phone',
    },
    {
      type: 'location',
      label: 'Location',
      value: 'India (Available Globally & Remote)',
      link: 'https://maps.google.com/?q=India',
      icon: 'map-pin',
    },
    {
      type: 'linkedin',
      label: 'LinkedIn',
      value: 'linkedin.com/in/harshitha-namala-a0a482318',
      link: 'https://www.linkedin.com/in/harshitha-namala-a0a482318',
      icon: 'linkedin',
    },
    {
      type: 'github',
      label: 'GitHub',
      value: 'github.com/harshithanamala04',
      link: 'https://github.com/harshithanamala04',
      icon: 'github',
    },
  ]);
}
